/* This file is automatically generated.  DO NOT EDIT! */
extern ld_emulation_xfer_type ld_elf_x86_64_emulation;
extern ld_emulation_xfer_type ld_elf_i386_emulation;
extern ld_emulation_xfer_type ld_i386linux_emulation;
extern ld_emulation_xfer_type ld_elf32btsmip_emulation;
extern ld_emulation_xfer_type ld_elf32ltsmip_emulation;
extern ld_emulation_xfer_type ld_elf64btsmip_emulation;
extern ld_emulation_xfer_type ld_elf32btsmipn32_emulation;
extern ld_emulation_xfer_type ld_elf32ltsmipn32_emulation;
extern ld_emulation_xfer_type ld_elf64ltsmip_emulation;
extern ld_emulation_xfer_type ld_elf_x86_64_fbsd_emulation;

#define EMULATION_LIST \
  &ld_elf_x86_64_emulation, \
  &ld_elf_i386_emulation, \
  &ld_i386linux_emulation, \
  &ld_elf32btsmip_emulation, \
  &ld_elf32ltsmip_emulation, \
  &ld_elf64btsmip_emulation, \
  &ld_elf32btsmipn32_emulation, \
  &ld_elf32ltsmipn32_emulation, \
  &ld_elf64ltsmip_emulation, \
  &ld_elf_x86_64_fbsd_emulation, \
  0
