/* -- This file is automatically generated -- */ 
/* 

  Copyright (C) 2002, 2004 ST Microelectronics, Inc.  All Rights Reserved. 

  This program is free software; you can redistribute it and/or modify it 
  under the terms of version 2 of the GNU General Public License as 
  published by the Free Software Foundation. 
  This program is distributed in the hope that it would be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

  Further, this software is distributed without any warranty that it is 
  free of the rightful claim of any third person regarding infringement 
  or the like.  Any license provided herein, whether implied or 
  otherwise, applies only to this software file.  Patent licenses, if 
  any, provided herein do not apply to combinations of this program with 
  other software, or any other product whatsoever. 
  You should have received a copy of the GNU General Public License along 
  with this program; if not, write the Free Software Foundation, Inc., 59 
  Temple Place - Suite 330, Boston MA 02111-1307, USA. 

  Contact information:  ST Microelectronics, Inc., 
  , or: 

  http://www.st.com 

  For further information regarding this notice, see: 

  http: 
*/ 

// AUTOMATICALLY GENERATED FROM MDS DATA BASE !!! 


// 
// Generate a list of literal classes and values for the ISA. 
///////////////////////////////////////////////////////// 

#include <stddef.h> 
#include "isa_lits_gen.h" 

main () 
{ 
  ISA_Lits_Begin(); 

  // ISA_Create_Lit_Class(name, type, [range,...] LIT_RANGE_END) 

  ISA_Create_Lit_Class("bkptnum", UNSIGNED, UnsignedBitRange(16), LIT_RANGE_END);
  LIT_RANGE lr_btarg1 = ISA_Create_Lit_Range("lr_btarg1", -0x800000LL, 0x7fffffLL, 2);
  ISA_Create_Lit_Class("btarg1", SIGNED, lr_btarg1, LIT_RANGE_END);
  LIT_RANGE lr_btarg2 = ISA_Create_Lit_Range("lr_btarg2", -0x1000000LL, 0xffffffLL, 1);
  ISA_Create_Lit_Class("btarg2", SIGNED, lr_btarg2, LIT_RANGE_END);
  ISA_Create_Lit_Class("gen_s32", SIGNED, SignedBitRange(32), LIT_RANGE_END);
  ISA_Create_Lit_Class("immed4", UNSIGNED, UnsignedBitRange(4), LIT_RANGE_END);
  ISA_Create_Lit_Class("immed5", UNSIGNED, UnsignedBitRange(5), LIT_RANGE_END);
  LIT_RANGE lr_wrap8 = ISA_Create_Lit_Range("lr_wrap8", 0x0LL, 0xffLL, 1, 4);
  ISA_Create_Lit_Class("immed8", SIGNED, lr_wrap8, LIT_RANGE_END);
  ISA_Create_Lit_Class("offset12", UNSIGNED, UnsignedBitRange(12), LIT_RANGE_END);
  ISA_Create_Lit_Class("offset12pc", UNSIGNED, UnsignedBitRange(12), LIT_RANGE_END);
  ISA_Create_Lit_Class("offset8", UNSIGNED, UnsignedBitRange(8), LIT_RANGE_END);
  LIT_RANGE lr_offset8cp = ISA_Create_Lit_Range("lr_offset8cp", 0x0LL, 0xffLL, 2);
  ISA_Create_Lit_Class("offset8cp", UNSIGNED, lr_offset8cp, LIT_RANGE_END);
  ISA_Create_Lit_Class("offset8pc", UNSIGNED, UnsignedBitRange(8), LIT_RANGE_END);
  ISA_Create_Lit_Class("opcode1d", UNSIGNED, UnsignedBitRange(4), LIT_RANGE_END);
  ISA_Create_Lit_Class("opcode1m", UNSIGNED, UnsignedBitRange(3), LIT_RANGE_END);
  ISA_Create_Lit_Class("opcode2", UNSIGNED, UnsignedBitRange(4), LIT_RANGE_END);
  ISA_Create_Lit_Class("option", UNSIGNED, UnsignedBitRange(8), LIT_RANGE_END);
  LIT_RANGE lr_rot = ISA_Create_Lit_Range("lr_rot", 0x0LL, 0x3LL, 3);
  ISA_Create_Lit_Class("rot", UNSIGNED, lr_rot, LIT_RANGE_END);
  LIT_RANGE lr_rotimm = ISA_Create_Lit_Range("lr_rotimm", 0x0LL, 0xfLL, 1);
  ISA_Create_Lit_Class("rotimm", UNSIGNED, lr_rotimm, LIT_RANGE_END);
  LIT_RANGE lr_wrap13 = ISA_Create_Lit_Range("lr_wrap13", -0xfffLL, 0xfffLL, 0);
  ISA_Create_Lit_Class("s13", SIGNED, lr_wrap13, LIT_RANGE_END);
  LIT_RANGE lr_wrap9 = ISA_Create_Lit_Range("lr_wrap9", -0xffLL, 0xffLL, 0);
  ISA_Create_Lit_Class("s9", SIGNED, lr_wrap9, LIT_RANGE_END);
  ISA_Create_Lit_Class("shfimml", UNSIGNED, UnsignedBitRange(5), LIT_RANGE_END);
  LIT_RANGE lr_wrap5 = ISA_Create_Lit_Range("lr_wrap5", 0x1LL, 0x20LL, 0);
  ISA_Create_Lit_Class("shfimmr", SIGNED, lr_wrap5, LIT_RANGE_END);
  ISA_Create_Lit_Class("ssat4", UNSIGNED, UnsignedBitRange(4), LIT_RANGE_END);
  ISA_Create_Lit_Class("ssat5", UNSIGNED, UnsignedBitRange(5), LIT_RANGE_END);
  ISA_Create_Lit_Class("swinum", UNSIGNED, UnsignedBitRange(24), LIT_RANGE_END);
  ISA_Create_Lit_Class("usat4", UNSIGNED, UnsignedBitRange(4), LIT_RANGE_END);
  ISA_Create_Lit_Class("usat5", UNSIGNED, UnsignedBitRange(5), LIT_RANGE_END);
/* This is now RegMask transformed as literals because targinfo does not yet support this feature. */
  ISA_Create_Lit_Class("reglist", UNSIGNED, UnsignedBitRange(16), LIT_RANGE_END);
 
  ISA_Lits_End(); 
  return 0; 
} 
