/* -- This file is automatically generated -- */ 
/* 

  Copyright (C) 2002, 2004 ST Microelectronics, Inc.  All Rights Reserved. 

  This program is free software; you can redistribute it and/or modify it 
  under the terms of version 2 of the GNU General Public License as 
  published by the Free Software Foundation. 
  This program is distributed in the hope that it would be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

  Further, this software is distributed without any warranty that it is 
  free of the rightful claim of any third person regarding infringement 
  or the like.  Any license provided herein, whether implied or 
  otherwise, applies only to this software file.  Patent licenses, if 
  any, provided herein do not apply to combinations of this program with 
  other software, or any other product whatsoever. 
  You should have received a copy of the GNU General Public License along 
  with this program; if not, write the Free Software Foundation, Inc., 59 
  Temple Place - Suite 330, Boston MA 02111-1307, USA. 

  Contact information:  ST Microelectronics, Inc., 
  , or: 

  http://www.st.com 

  For further information regarding this notice, see: 

  http: 
*/ 

// AUTOMATICALLY GENERATED FROM MDS DATA BASE !!! 
//  
//  Generate relocations information
///////////////////////////////////////

#include <stdio.h>

#include <stddef.h>
#include "isa_relocs_gen.h"

main()
{
  ISA_Relocs_Begin();

  // ISA_Create_Reloc_Type( name, main symbol, second symbol, addend, pcrel,
  //                        gprel, gotrel)

  RELOC_TYPE rel_none =
      ISA_Create_Reloc_Type("none",R_NO_MAIN_SYMBOL,R_NO_SECOND_SYMBOL,R_NO_ADDEND,
			    R_NO_PCREL,R_NO_GPREL,R_NO_GOTREL);
  RELOC_TYPE rel_s_a = 
    ISA_Create_Reloc_Type("s_a",R_MAIN_SYMBOL,R_NO_SECOND_SYMBOL,R_ADDEND,
			  R_NO_PCREL,R_NO_GPREL,R_NO_GOTREL);
  RELOC_TYPE rel_s_a_pc =
      ISA_Create_Reloc_Type("s_a_pc",R_MAIN_SYMBOL,R_NO_SECOND_SYMBOL,R_ADDEND,
			    R_PCREL,R_NO_GPREL,R_NO_GOTREL);

  BITFIELD bf_0_12 = ISA_Create_BitField("bf_0_12",0,12);
  BITFIELD bf_0_24 = ISA_Create_BitField("bf_0_24",0,24);
  BITFIELD bf_0_4  = ISA_Create_BitField("bf_0_4",0,4);
  BITFIELD bf_8_4  = ISA_Create_BitField("bf_8_4",8,4);
  BITFIELD bf_24_1 = ISA_Create_BitField("bf_24_1",24,1);

 // ISA_VIRTUAL_RELOC_TYPE = ISA_Create_Reloc(
  //                            name,syntax, lit_class_type,
  //                            overflow, right_shift, underflow,
  //                             RELOC_TYPE, ... bitfields, BIT_FIELD_END) 

  ISA_VIRTUAL_RELOC_TYPE R_ARM_CALL  =
                   ISA_Create_Reloc(1,"R_ARM_CALL", "",
 		   ISA_RELOC_NO_OVERFLOW, ISA_RELOC_UNDERFLOW, 1,
		   rel_s_a_pc, ISA_RELOC_RLLIB_DYNPLT, 1, bf_0_24, 2, bf_24_1, BITFIELD_END);

  ISA_VIRTUAL_RELOC_TYPE R_ARM_JUMP24  =
                   ISA_Create_Reloc(2,"R_ARM_JUMP24", "",
 		   ISA_RELOC_NO_OVERFLOW, ISA_RELOC_UNDERFLOW, 2,
		   rel_s_a_pc, ISA_RELOC_RLLIB_DYNPLT, 3, bf_0_24, BITFIELD_END);

  ISA_VIRTUAL_RELOC_TYPE R_ARM_OFFSET12  =
                   ISA_Create_Reloc(3,"offset12", "",
 		   ISA_RELOC_NO_OVERFLOW, ISA_RELOC_NO_UNDERFLOW, 0,
		   rel_s_a, ISA_RELOC_RLLIB_UNKNOWN, 4, bf_0_12, BITFIELD_END);

  ISA_VIRTUAL_RELOC_TYPE R_ARM_OFFSET12PC  =
                   ISA_Create_Reloc(4,"offset12PC", "=",
 		   ISA_RELOC_NO_OVERFLOW, ISA_RELOC_NO_UNDERFLOW, 0,
		   rel_s_a_pc, ISA_RELOC_RLLIB_UNKNOWN, 5, bf_0_12, BITFIELD_END);

  ISA_VIRTUAL_RELOC_TYPE R_ARM_OFFSET8  =
                   ISA_Create_Reloc(5,"offset8", "",
 		   ISA_RELOC_NO_OVERFLOW, ISA_RELOC_NO_UNDERFLOW, 0,
		   rel_s_a, ISA_RELOC_RLLIB_UNKNOWN, 6, bf_0_4, 7, bf_8_4, BITFIELD_END);

  ISA_VIRTUAL_RELOC_TYPE R_ARM_OFFSET8PC  =
                   ISA_Create_Reloc(6,"offset8PC", "=",
 		   ISA_RELOC_NO_OVERFLOW, ISA_RELOC_NO_UNDERFLOW, 0,
		   rel_s_a_pc, ISA_RELOC_RLLIB_UNKNOWN, 8, bf_0_4, 9, bf_8_4, BITFIELD_END);


  ///////////////////////////////////////////////////////
  // Defining subset relocations
  ///////////////////////////////////////////////////////

  ISA_Reloc_Subset(
      ISA_SUBSET_armv5e,
      R_ARM_CALL,
      R_ARM_JUMP24,
      R_ARM_OFFSET12,
      R_ARM_OFFSET12PC,
      R_ARM_OFFSET8,
      R_ARM_OFFSET8PC,
      NULL);

  ISA_Reloc_Subset(
      ISA_SUBSET_armv6,
      R_ARM_CALL,
      R_ARM_JUMP24,
      R_ARM_OFFSET12,
      R_ARM_OFFSET12PC,
      R_ARM_OFFSET8,
      R_ARM_OFFSET8PC,
      NULL);

  ISA_Relocs_End();
}

