
#
# Define the BUILD platform
#
BUILD_OS    = SUNOS5
BUILD_ARCH  = SPARC
BUILD_ABI   = I32BIT

#
# Define the HOST platform (same as BUILD by default)
#
#HOST_OS     = 
#HOST_ARCH   = 
#HOST_ABI    = 

#
# Define the TARGET
#
BUILD_TARGET = ST100
