/* Generated automatically by the program `gencodes'
   from the machine description file `md'.  */

#ifndef GCC_INSN_CODES_H
#define GCC_INSN_CODES_H

enum insn_code {
  CODE_FOR_addcg_insn = 5,
  CODE_FOR_addsi3 = 6,
  CODE_FOR_subsi3 = 7,
  CODE_FOR_sminsi3 = 8,
  CODE_FOR_smaxsi3 = 9,
  CODE_FOR_uminsi3 = 10,
  CODE_FOR_umaxsi3 = 11,
  CODE_FOR_andsi3 = 12,
  CODE_FOR_iorsi3 = 13,
  CODE_FOR_xorsi3 = 14,
  CODE_FOR_ashlsi3 = 15,
  CODE_FOR_ashrsi3 = 16,
  CODE_FOR_lshrsi3 = 17,
  CODE_FOR_negsi2 = 18,
  CODE_FOR_one_cmplsi2 = 19,
  CODE_FOR_dummy_mulsi3 = 23,
  CODE_FOR_extendhisi2 = 39,
  CODE_FOR_extendqisi2 = 40,
  CODE_FOR_ldhu_insn = 41,
  CODE_FOR_zero_extendhiqi2 = 42,
  CODE_FOR_cmpcc_insn = 43,
  CODE_FOR_cmpcc_br_insn = 44,
  CODE_FOR_mfb_cc_insn = 46,
  CODE_FOR_mfb_cc_br_insn = 47,
  CODE_FOR_slctf_insn = 49,
  CODE_FOR_jump = 54,
  CODE_FOR_indirect_jump = 55,
  CODE_FOR_tablejump = 56,
  CODE_FOR_return = 59,
  CODE_FOR_nop = 60,
  CODE_FOR_bundle_barrier = 61,
  CODE_FOR_movsi = 64,
  CODE_FOR_movhi = 65,
  CODE_FOR_movqi = 66,
  CODE_FOR_movsf = 67,
  CODE_FOR_adddi3 = 69,
  CODE_FOR_abssi2 = 70,
  CODE_FOR_mulsi3 = 71,
  CODE_FOR_zero_extendhisi2 = 74,
  CODE_FOR_absdf2 = 75,
  CODE_FOR_abssf2 = 76,
  CODE_FOR_negsf2 = 77,
  CODE_FOR_negdf2 = 78,
  CODE_FOR_cmpsi = 79,
  CODE_FOR_reload_incc = 80,
  CODE_FOR_reload_incc_br = 81,
  CODE_FOR_reload_outcc = 82,
  CODE_FOR_reload_outcc_br = 83,
  CODE_FOR_movsicc = 84,
  CODE_FOR_seq = 85,
  CODE_FOR_sne = 86,
  CODE_FOR_sgt = 87,
  CODE_FOR_sgtu = 88,
  CODE_FOR_slt = 89,
  CODE_FOR_sltu = 90,
  CODE_FOR_sge = 91,
  CODE_FOR_sgeu = 92,
  CODE_FOR_sle = 93,
  CODE_FOR_sleu = 94,
  CODE_FOR_beq = 95,
  CODE_FOR_bne = 96,
  CODE_FOR_bgt = 97,
  CODE_FOR_bgtu = 98,
  CODE_FOR_blt = 99,
  CODE_FOR_bltu = 100,
  CODE_FOR_bge = 101,
  CODE_FOR_bgeu = 102,
  CODE_FOR_ble = 103,
  CODE_FOR_bleu = 104,
  CODE_FOR_call = 105,
  CODE_FOR_call_value = 106,
  CODE_FOR_prologue = 107,
  CODE_FOR_epilogue = 108,
  CODE_FOR_nothing
};

#endif /* GCC_INSN_CODES_H */
