case GSBI_IX86_BUILTIN_VADDSUBPD256:
*iopc = INTRN_VADDSUBPD256;
break;
case GSBI_IX86_BUILTIN_VBLENDVPD256:
*iopc = INTRN_VBLENDVPD256;
break;
case GSBI_IX86_BUILTIN_VDPPS:
*iopc = INTRN_VDPPS;
break;
case GSBI_IX86_BUILTIN_VADDSUBPS256:
*iopc = INTRN_VADDSUBPS256;
break;
case GSBI_IX86_BUILTIN_VANDNPD256:
*iopc = INTRN_VANDNPD256;
break;
case GSBI_IX86_BUILTIN_VANDNPS:
*iopc = INTRN_VANDNPS;
break;
case GSBI_IX86_BUILTIN_VADDPS256:
*iopc = INTRN_VADDPS256;
break;
case GSBI_IX86_BUILTIN_VANDPS256:
*iopc = INTRN_VANDPS256;
break;
case GSBI_IX86_BUILTIN_VANDPD256:
*iopc = INTRN_VANDPD256;
break;
case GSBI_IX86_BUILTIN_VBLENDPS:
*iopc = INTRN_VBLENDPS;
break;
case GSBI_IX86_BUILTIN_VBLENDPD:
*iopc = INTRN_VBLENDPD;
break;
case GSBI_IX86_BUILTIN_VADDPD256:
*iopc = INTRN_VADDPD256;
break;
case GSBI_IX86_BUILTIN_VDIVPS:
*iopc = INTRN_VDIVPS;
break;
case GSBI_IX86_BUILTIN_VBLENDVPS256:
*iopc = INTRN_VBLENDVPS256;
break;
case GSBI_IX86_BUILTIN_VDIVPD256:
*iopc = INTRN_VDIVPD256;
break;
