#
#  Makefile for libSYS
#

#
# Define the BUILD HOST and TARGET platforms
#
include ../Makefile.platforms

#
# Define the build parameters that are common to most of the modules
# (can be overwritten below
#
include ../Makefile.build


#
#  Define build parameters
#
BUILD_BASE     = $(BUILD_TOT)/libSYS

#
# Include a top-level makefile which will then include the module
# specific Makefile.gsetup
#
include $(BUILD_TOT)/Makefile.gsetup
