/*
  Copyright (C) 2007, STMicroelectronics, All Rights Reserved.

  This program is free software; you can redistribute it and/or modify it
  under the terms of version 2 of the GNU General Public License as
  published by the Free Software Foundation.

  This program is distributed in the hope that it would be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

  Further, this software is distributed without any warranty that it is
  free of the rightful claim of any third person regarding infringement 
  or the like.  Any license provided herein, whether implied or 
  otherwise, applies only to this software file.  Patent licenses, if 
  any, provided herein do not apply to combinations of this program with 
  other software, or any other product whatsoever.  

  You should have received a copy of the GNU General Public License along
  with this program; if not, write the Free Software Foundation, Inc., 59
  Temple Place - Suite 330, Boston MA 02111-1307, USA.
*/

#ifndef PQS_TARGET_included
#define PQS_TARGET_included

/* ====================================================================
 * ====================================================================
 *
 * Module: pqs_target.h
 *
 * Description:
 *
 * pqs target-specific interface
 *
 * ====================================================================
 * ====================================================================
 */

// PQSTARG_classify_instruction
//
// Classify the predicate behaviour
// of an instruction for the Predicate Query System.
// The following classifications can be made:
//  1.  It defines a predicate, in terms of a predicated
//      comparison between two values.
//      Add_Predicate_Cmp_Def() is used for this case.
//  2.  It copies another variable, that may potentially be
//      a predicate.
//      Add_Copy() is used for this case.
//  3.  It initializes a predicate to true or false.
//      Set_True()/Set_False() are used for this case.
//
// For target instructions that define a predicate and
// its complement, Add_Predicate_Cmp_Def () should be called
// twice: once for each result, negating the comparison for
// the complemented result.
// For target instructions that are (parallel) conditional
// overwrite, these should be treated as a sequence of
// read-modify-write  operations.
extern void PQSTARG_classify_instruction (PQS_MANAGER *pqsm, OP *op);

// PQSTARG_sets_results_if_qual_true
//
// Indicates that the value of the result is always generated by this
// instruction when the predicate is true.
// For normal and unconditional operations this is always TRUE.
// For parallel compare types it is false, because the result value
// of this instruction may be "overridden" by another instruction.
extern BOOL PQSTARG_sets_results_if_qual_true(OP *op);

// PQSTARG_target_synthesized_info
//
// A hook to allow the creation of any target-specific PQS information
// that is required.  For example, implicit instruction operands that
// must be declared to the PQS.
extern void PQSTARG_target_synthesized_info (PQS_MANAGER *pqsm);

#endif

