echo '#include "version.h"'
echo 'const char *const cset_id = "";'
echo 'const char *const build_root = "";'
echo 'const char *const build_host = "";'
echo 'const char *const build_user = "";'
echo 'const char *const build_date = "";'
