{/*VADDSUBPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VADDSUBPD256",NULL, NULL},
{/*VBLENDVPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VBLENDVPD256",NULL, NULL},
{/*VDPPS*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VDPPS",NULL, NULL},
{/*VADDSUBPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VADDSUBPS256",NULL, NULL},
{/*VANDNPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VANDNPD256",NULL, NULL},
{/*VANDNPS*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VANDNPS",NULL, NULL},
{/*VADDPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VADDPS256",NULL, NULL},
{/*VANDPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VANDPS256",NULL, NULL},
{/*VANDPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VANDPD256",NULL, NULL},
{/*VBLENDPS*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VBLENDPS",NULL, NULL},
{/*VBLENDPD*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VBLENDPD",NULL, NULL},
{/*VADDPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VADDPD256",NULL, NULL},
{/*VDIVPS*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VDIVPS",NULL, NULL},
{/*VBLENDVPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VBLENDVPS256",NULL, NULL},
{/*VDIVPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VDIVPD256",NULL, NULL},
