{/*VSQRTPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VSQRTPD256",NULL, NULL},
{/*VBLENDPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VBLENDPD256",NULL, NULL},
{/*VPERMILPS128*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VPERMILPS128",NULL, NULL},
{/*VADDSUBPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VADDSUBPS256",NULL, NULL},
{/*VUNPCKLPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VUNPCKLPD256",NULL, NULL},
{/*VZEROALL256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V,"VZEROALL256",NULL, NULL},
{/*VCVTTPD2DQ256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16I4,"VCVTTPD2DQ256",NULL, NULL},
{/*VINSERTF128D*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VINSERTF128D",NULL, NULL},
{/*VMULPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VMULPS256",NULL, NULL},
{/*VUNPCKHPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VUNPCKHPD256",NULL, NULL},
{/*VMASKMOVPS128ST*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V,"VMASKMOVPS128ST",NULL, NULL},
{/*VMOVUPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VMOVUPD256",NULL, NULL},
{/*VCMPSD*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F8,"VCMPSD",NULL, NULL},
{/*VMOVUPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VMOVUPS256",NULL, NULL},
{/*VHADDPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VHADDPD256",NULL, NULL},
{/*VTESTPD128C*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F8,"VTESTPD128C",NULL, NULL},
{/*VADDPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VADDPS256",NULL, NULL},
{/*VTESTPS256Z*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VTESTPS256Z",NULL, NULL},
{/*VEXTRACTF128D*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F8,"VEXTRACTF128D",NULL, NULL},
{/*VPERMILPD128*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F8,"VPERMILPD128",NULL, NULL},
{/*VANDPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VANDPS256",NULL, NULL},
{/*VCMPPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VCMPPS256",NULL, NULL},
{/*VANDPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VANDPD256",NULL, NULL},
{/*VCVTPD2DQ256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16I4,"VCVTPD2DQ256",NULL, NULL},
{/*VRCPPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VRCPPS256",NULL, NULL},
{/*VHADDPS*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VHADDPS",NULL, NULL},
{/*VMAXPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VMAXPD256",NULL, NULL},
{/*VMASKMOVPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VMASKMOVPD256",NULL, NULL},
{/*VBLENDPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VBLENDPS256",NULL, NULL},
{/*VUNPCKHPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VUNPCKHPS256",NULL, NULL},
{/*VTESTPS256C*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VTESTPS256C",NULL, NULL},
{/*VINSERTF128F*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VINSERTF128F",NULL, NULL},
{/*VMASKMOVPD128ST*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V,"VMASKMOVPD128ST",NULL, NULL},
{/*VHSUBPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VHSUBPS256",NULL, NULL},
{/*VPERMILPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VPERMILPD256",NULL, NULL},
{/*VMOVDQA256ST*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V,"VMOVDQA256ST",NULL, NULL},
{/*VMASKMOVPD128*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F8,"VMASKMOVPD128",NULL, NULL},
{/*VCVTDQ2PD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VCVTDQ2PD256",NULL, NULL},
{/*VADDPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VADDPD256",NULL, NULL},
{/*VINSERTF128I*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32I4,"VINSERTF128I",NULL, NULL},
{/*VSUBPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VSUBPS256",NULL, NULL},
{/*VMOVSLDUP256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VMOVSLDUP256",NULL, NULL},
{/*VPERMILPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VPERMILPS256",NULL, NULL},
{/*VCVTPD2PS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VCVTPD2PS256",NULL, NULL},
{/*VROUNDPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VROUNDPD256",NULL, NULL},
{/*VPERMILPD128VAR*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F8,"VPERMILPD128VAR",NULL, NULL},
{/*VMASKMOVPD256ST*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V,"VMASKMOVPD256ST",NULL, NULL},
{/*VPERM2F128S*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VPERM2F128S",NULL, NULL},
{/*VMULPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VMULPD256",NULL, NULL},
{/*VPERM2F128D*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VPERM2F128D",NULL, NULL},
{/*VTESTPD256NZC*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_I4,"VTESTPD256NZC",NULL, NULL},
{/*VRSQRTPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VRSQRTPS256",NULL, NULL},
{/*VDPPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VDPPS256",NULL, NULL},
{/*VMAXPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VMAXPS256",NULL, NULL},
{/*VBROADCAST128S*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VBROADCAST128S",NULL, NULL},
{/*VTESTPD256C*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VTESTPD256C",NULL, NULL},
{/*VMASKMOVPS128*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VMASKMOVPS128",NULL, NULL},
{/*VBROADCASTSS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VBROADCASTSS256",NULL, NULL},
{/*VADDSUBPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VADDSUBPD256",NULL, NULL},
{/*VSQRTPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VSQRTPS256",NULL, NULL},
{/*VTESTPS128NZC*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_I4,"VTESTPS128NZC",NULL, NULL},
{/*VBLENDVPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VBLENDVPD256",NULL, NULL},
{/*VMINPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VMINPS256",NULL, NULL},
{/*VTESTPD128NZC*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_I4,"VTESTPD128NZC",NULL, NULL},
{/*VANDNPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VANDNPD256",NULL, NULL},
{/*VXORPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VXORPS256",NULL, NULL},
{/*VBROADCASTSD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VBROADCASTSD256",NULL, NULL},
{/*VSHUFPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32I4,"VSHUFPS256",NULL, NULL},
{/*VCVTPS2DQ256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32I4,"VCVTPS2DQ256",NULL, NULL},
{/*VEXTRACTF128S*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VEXTRACTF128S",NULL, NULL},
{/*VPERMILPD256VAR*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VPERMILPD256VAR",NULL, NULL},
{/*VHSUBPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VHSUBPD256",NULL, NULL},
{/*VZEROUPPER256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V,"VZEROUPPER256",NULL, NULL},
{/*VCMPPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VCMPPD256",NULL, NULL},
{/*VBROADCAST128D*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VBROADCAST128D",NULL, NULL},
{/*VMOVMSKPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_I4,"VMOVMSKPD256",NULL, NULL},
{/*VMASKMOVPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VMASKMOVPS256",NULL, NULL},
{/*VMOVMSKPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_I4,"VMOVMSKPS256",NULL, NULL},
{/*VDIVPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VDIVPS256",NULL, NULL},
{/*VSUBPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VSUBPD256",NULL, NULL},
{/*VMINPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VMINPD256",NULL, NULL},
{/*VLDDQU256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32I4,"VLDDQU256",NULL, NULL},
{/*VPERM2F128SI*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32I4,"VPERM2F128SI",NULL, NULL},
{/*VTESTPS128C*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VTESTPS128C",NULL, NULL},
{/*VROADCASTSS128*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VROADCASTSS128",NULL, NULL},
{/*VCMPPS128*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VCMPPS128",NULL, NULL},
{/*VMOVNTDQ256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V,"VMOVNTDQ256",NULL, NULL},
{/*VUNPCKLPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VUNPCKLPS256",NULL, NULL},
{/*VORPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VORPS256",NULL, NULL},
{/*VBLENDVPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VBLENDVPS256",NULL, NULL},
{/*VPERMILPS256VAR*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VPERMILPS256VAR",NULL, NULL},
{/*VCMPSS128*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VCMPSS128",NULL, NULL},
{/*VEXTRACTF128I*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16I4,"VEXTRACTF128I",NULL, NULL},
{/*VORPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VORPD256",NULL, NULL},
{/*VANDNPS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VANDNPS256",NULL, NULL},
{/*VDIVPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VDIVPD256",NULL, NULL},
{/*VXORPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VXORPD256",NULL, NULL},
{/*VCVTDQ2PS256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VCVTDQ2PS256",NULL, NULL},
{/*VPERMILPS128VAR*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VPERMILPS128VAR",NULL, NULL},
{/*VMASKMOVPS256ST*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V,"VMASKMOVPS256ST",NULL, NULL},
{/*VTESTPS256NZC*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_I4,"VTESTPS256NZC",NULL, NULL},
{/*VTESTPD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F4,"VTESTPD256",NULL, NULL},
{/*VCMPPD128*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F8,"VCMPPD128",NULL, NULL},
{/*VTESTPD128*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VTESTPD128",NULL, NULL},
{/*VCVTPS2PD256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VCVTPS2PD256",NULL, NULL},
{/*VMOVDDUP256*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V32F8,"VMOVDDUP256",NULL, NULL},
{/*VTESTPS128Z*/
BYVAL, PURE, NO_SIDEEFFECTS, DOES_RETURN, NOT_ACTUAL, CGINTRINSIC,
IRETURN_V16F4,"VTESTPS128Z",NULL, NULL},
